### ISSUE TITLE
Make account number/id type consistent, preferably strings

### ISSUE THREAD

**Issue by nicmcd** [alexgolec/tda-api#13]
The API currently has mixed expectations of the format of account numbers. TDA happens to use numeric account numbers (currently), but this may not always be true. There are places in the code that assume numeric numbers for comparison reasons (i.e., in extract_order_id). There are other places that are OK with accepting string based account ids. 

The most robust mechanism would be to always use strings, for two reasons:
1. HTTP text is string-based anyways
2. Strings will protect against future issues when/if TDA chooses to have not numeric account ids.

**Comment by alexgolec** [comment]
As a comment, I'm willing to commit to using integers as IDs because financial institutions like TDA almost always use integer account IDs. Also, the documentation and examples have always used integers, and I'd like to maintain consistency for existing users, who I assume will follow this practice and use integers. 

I'm currently thinking of requiring all IDs to be integers for the sake of consistency.

**Comment by nicmcd** [comment]
"almost always use integer account IDs"
People should be willing to wrap a number with `"` if it gives their application future reliability. 

You could always accept ints or strings, but convert to strings and operate on strings internally. The only incompatibility will be the return value you give.

**Comment by alexgolec** [comment]
Man, it's been a while since I've had a good Google-tier CL review. I'll ponder this and come up with a design soon.

**Comment by alexgolec** [comment]
Got a PR that implements this, PTAL
