### ISSUE TITLE
401 unauthorized errors in Ubuntu, but works in Windows

### ISSUE THREAD

**Issue by dpappyp** [alexgolec/tda-api#238]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
Everything works fine with token generation and use for streaming quotes and placing orders when being run in Python in Windows.  It fails, however, with 401 unauthorized errors in Ubuntu.  I've tried using the same token that works in Windows and also generating a new token in Ubuntu.  I've also tried deleting the app registered with TD Ameritrade and starting over, but only get the same results.

**Code to Reproduce**
import config
import json
from tda import auth, client
from tda.auth import easy_client
from tda.client import Client
from tda.orders.equities import equity_buy_market, equity_sell_market
from tda.orders.common import Duration, Session

try:
    c = auth.client_from_token_file(config.token_path, config.api_key)
except FileNotFoundError:
    c = auth.client_from_manual_flow(
        config.api_key, config.redirect_uri, config.token_path, asyncio=False, token_write_func=None)

try:
    r = c.place_order(
        config.account_id,  
        equity_buy_market('SHY', 1)
            .set_duration(Duration.DAY)
            .set_session(Session.NORMAL)
            .build())
    order_submitted = True
except:
    order_submitted = False

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
Order is placed

**Actual Behavior**
Response [401 Unauthorized]>
{'error': 'The API key in request query param is either null or blank or invalid.'}

**Error/Exception Log, If Applicable**
See here to learn how to turn on debug logging: https://tda-api.readthedocs.io/en/latest/help.html

**Comment by friendliestdev** [comment]
There is mismatch between `authlib` and `httpx` that is causing this issue. A partial fix was made in #237, but since the [`setup.py`](https://github.com/alexgolec/tda-api/blob/2272b671e64fa5ef19f5bc0708675bd8f28af5af/setup.py#L35) wasn't updated, `pip` just installs the newest version. Try a `pip install httpx==0.18.1` to downgrade to a working version. I assume your windows install already had an older version and ubuntu is a newer install.

**Comment by alexgolec** [comment]
This is the correct response. I brought this issue to the attention of the `authlib` maintainers, and they acknowledge the issue and say it is fixed in their master tree. No word on when it will be released yet. 

In the meantime, `tda-api` has been updated to require the last safe version of `authlib`. You can install this version as follows: 

    pip uninstall tda-api authlib
    pip install --upgrade tda-api
