### ISSUE TITLE
Definition for 'SEAMLESS' Session Type

### ISSUE THREAD

**Issue by jfw225** [alexgolec/tda-api#43]
Under "Session and Duration" in the OrderBuilder Reference, you linked here to let you know what a seamless session is. Basically, it's for whenever the market is open for trading (DAY + EXT).

https://www.tdameritrade.com/retail-en_us/resources/pdf/AMTD183.pdf <-- ctrl + f 'seamless' should help.

**Comment by Emtymister** [comment]
Also, you misspelled seamless when you enumerated it.

**Comment by alexgolec** [comment]
Ha! Thanks for the tip. I'll make the change and push it in the next release.

**Comment by Emtymister** [comment]
Sure thing! Thanks for creating this library. Also, I noticed that you work with machine learning. I'm currently an undergraduate at Cornell studying Mathematics and Computer Science, but I'm particularly interested in how machine learning can be applied to the financial markets. Have you been able to successfully unify this API with any aspects of ML? I only ask because that is the exact reason why I sought out a module like yours in the first place.

**Comment by alexgolec** [comment]
This is a great question, but not entirely appropriate for a GH issue discussion. We have a Discord for random discussions, though: discord.gg/nfrd9gh
